sudo: required
services:
  - docker

before_install:
  - docker build -t vedlatha111/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run vedlatha111/react-test npm test -- --coverage

after_success:
  - docker build -t vedlatha111/multi-client ./client
  - docker build -t vedlatha111/multi-nginx ./nginx
  - docker build -t vedlatha111/multi-server ./server
  - docker build -t vedlatha111/multi-worker ./worker
  
  # log into the docker cLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #  take those images and push them to docker hub
  - docker push vedlatha111/multi-client
  - docker push vedlatha111/multi-nginx
  - docker push vedlatha111/multi-server
  - docker push vedlatha111/multi-worker
 

